### ISSUE TITLE
Loop

### ISSUE THREAD

**Issue by ovalseven** [zefie/BeatnikProject2019#1]
This would be perfect to associate with rmf and mid files if Loop weren't enabled by default.

**Comment by zefie** [comment]
Apologies for the delay. The application was actually designed to store some settings, including the status of the loop option, however there was a bug that prevented the UserPrefs.xml settings from applying. The latest release (https://github.com/zefie/BeatnikProject2019/releases/tag/v1.1.7645.33490) should address this. The first time you run, loop will likely still be enabled, but once you uncheck it and close the application, all future launches should start with looping off, until you turn it back on.
