### ISSUE TITLE
Theme song progress indicator after the user's accent colors

### ISSUE THREAD

**Issue by SKCro** [zefie/BeatnikProject2019#12]
Just like the title says - if the user is on Windows 10, the progress indicator can be themed based off of the user's accent color.
If the user is on Windows 7 or 8, their Aero Glass color can be used instead. If the user is on an older system (or the program is using the classic theme via WindowBlinds), active titlebar gradient colors can be used instead.

Mockup:
![image](https://github.com/zefie/BeatnikProject2019/assets/55817746/92d500a3-3b95-4361-8f81-a3c3054e5c17)
<sub>In this example, my accent color is `#004488`. The gradient is from `#004488` to `#002244`.</sub>

This could probably be implemented by checking the user's Windows version and for the presence of an accent color. Not sure how Windows 10 stores the user's accent color though.

**Comment by zefie** [comment]
Addressed for Win10+ in 47f8d139dad9cc003f6760806f1fb38b4b2a6339
