### ISSUE TITLE
Remove admin requirement

### ISSUE THREAD

**Issue by Sgeo** [zefie/BeatnikProject2019#7]
I was able to replace the GetWindowsDirectory call with a GetCurrentDirectory call, by:

- Hex editing the name of the call in the .ocx
- Using x32dbg to swap these two assembly instructions in the three places where that function was used:

1. `push eax`
2. `push 0x104`

The attached is the resulting .ocx file, and a .1337 file that shows the assembly changes (not the import change)

[beatnikx_portable.zip](https://github.com/zefie/BeatnikProject2019/files/10079272/beatnikx_portable.zip)

**Comment by zefie** [comment]
Sweet, added in 616b1a8ac23682bd50467f0592fb757396e60f2d. Thanks!
