### ISSUE TITLE
Output as wav file?

### ISSUE THREAD

**Issue by misaka00251** [zefie/BeatnikProject2019#8]
Just like the title, as for now there's no way to output as other formats.

**Comment by SKCro** [comment]
I just use Audacity's loopback feature and record the player, then trim out the silence. If you do this, make sure to mute notifications from things like Discord or else those will make their way into the file as well.

**Comment by zefie** [comment]
The beatnik.ocx controls all of the audio output, which is why we don't have any fancy options like exporting WAV, or changing audio devices.
